-- TABLA USUARIO
CREATE TABLE USUARIO(
    Nombre VARCHAR(20) NOT NULL,
	Id INT UNSIGNED NOT NULL,
    contra VARCHAR(20) NOT NULL,
    nombre_usuario VARCHAR(20) NOT NULL,
    cell INT UNSIGNED NOT NULL,
    fechan VARCHAR (20) NOT NULL,
    tipo_cuenta VARCHAR (20) NOT NULL,
    CONSTRAINT USUARIO_pk PRIMARY KEY (Id)
);

-- TABLA MUDANZA
CREATE TABLE MUDANZA (
  Id INT UNSIGNED NOT NULL,
  persona INT UNSIGNED NOT NULL,
  conductor INT UNSIGNED NOT NULL,
  ayudande1 INT NULL,
  ayudante2 INT NULL,
  direccion_partida VARCHAR (20) NOT NULL, 
  direccion_llegada VARCHAR (20) NOT NULL,
  fecha VARCHAR (20),
  hora VARCHAR (20),
  cant_ayudantes INT UNSIGNED NOT NULL,
  CONSTRAINT MUDANZA_pk PRIMARY KEY (Id),
  CONSTRAINT MUDANZA_USUARIO_fk FOREIGN KEY (persona) REFERENCES USUARIO(Id)
);

-- TABLA ARTICULOS DE UNA MUDANZA
CREATE TABLE ARTICULOSMUDANZA (
 nombre_art VARCHAR(20) NOT NULL,
 largo INT UNSIGNED NOT NULL,
 ancho INT UNSIGNED NOT NULL,
 alto INT UNSIGNED NOT NULL,
 peso INT UNSIGNED NOT NULL,
 idmudanza INT UNSIGNED NOT NULL, 
 CONSTRAINT ARTICULOSMUDANZA_MUDANZA_fk FOREIGN KEY (idmudanza) REFERENCES MUDANZA(Id)
<<<<<<< HEAD
=======
);




CREATE TABLE Ivanhp (
 nombre_art1 VARCHAR(20) NOT NULL,
 largo1 INT UNSIGNED NOT NULL,
 ancho1 INT UNSIGNED NOT NULL,
 alto1 INT UNSIGNED NOT NULL,
 peso1 INT UNSIGNED NOT NULL,
 idmudanza1 INT UNSIGNED NOT NULL, 
 CONSTRAINT ARTICULOSMUDANZA_MUDANZA_fk FOREIGN KEY (idmudanza) REFERENCES MUDANZA(Id)
>>>>>>> 4aa81a9 (Proyecto subido)
);